import { getDb } from '../src/database.js';

// Removed Express, bodyParser, Datastore, async, fs, os, path, and custom createDirectory logic

export async function getAllCategories() {
    const db = await getDb();
    const categoriesQuery = db.exec("SELECT * FROM categories");
    if (categoriesQuery.length === 0 || categoriesQuery[0].values.length === 0) {
        return [];
    }
    const columns = categoriesQuery[0].columns;
    return categoriesQuery[0].values.map(row => {
        const obj = {};
        columns.forEach((col, i) => obj[col] = row[i]);
        return obj;
    });
}

export async function addCategory(categoryData) {
    const db = await getDb();
    // Assuming categoryData contains { name: 'Category Name' }
    // _id will be auto-generated by SQLite if not provided and table is set up for it,
    // or we can generate it like before.
    // For consistency with original, let's generate _id.
    const newId = categoryData._id || Math.floor(Date.now() / 1000);

    // Ensure categoryData has a name, as it's NOT NULL UNIQUE in schema
    if (!categoryData.name) {
        throw new Error("Category name is required.");
    }

    try {
        db.run(
            'INSERT INTO categories (_id, name) VALUES (?, ?)',
            [newId, categoryData.name]
        );
        return { _id: newId, name: categoryData.name };
    } catch (e) {
        // Handle potential unique constraint violation for name
        if (e.message.includes("UNIQUE constraint failed: categories.name")) {
            throw new Error(`Category with name "${categoryData.name}" already exists.`);
        }
        throw e; // Re-throw other errors
    }
}

export async function deleteCategory(categoryId) {
    const db = await getDb();
    const parsedCategoryId = parseInt(categoryId);
    db.run('DELETE FROM categories WHERE _id = ?', [parsedCategoryId]);
    return { message: "Category deleted successfully", deletedId: parsedCategoryId };
}

export async function updateCategory(categoryData) {
    const db = await getDb();
    const { id, name } = categoryData; // Assuming categoryData is { id: 123, name: "New Name" }

    if (!id) {
        throw new Error("Category ID is required for update.");
    }
    if (!name) {
        throw new Error("Category name is required for update.");
    }
    const parsedId = parseInt(id);

    try {
        db.run(
            'UPDATE categories SET name = ? WHERE _id = ?',
            [name, parsedId]
        );
        return { message: "Category updated successfully", updatedId: parsedId, name: name };
    } catch (e) {
        if (e.message.includes("UNIQUE constraint failed: categories.name")) {
            throw new Error(`Another category with name "${name}" already exists.`);
        }
        throw e;
    }
}